---
repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.12.2 # put latest release tag from https://github.com/ansible-community/ansible-lint/releases/
    hooks:
      - id: ansible-lint
        args:
          - "--fix"
        files: \.(yaml|yml)$
