---

- name: "update − system packages"
  package: name="*" state=latest

- name: "update − set facts for current distribution if using dnf"
  set_fact:
    package: "dnf-automatic"
    config_path: dnf/automatic.conf
    config_var: "{{ dnf_automatic }}"
    service: "dnf-automatic.timer"
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 8) or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version|int == 8) or
        (ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 30)

- name: "update − set facts for current distribution is using yum"
  set_fact:
    package: "yum-cron"
    config_path: yum/yum-cron.conf
    config_var: "{{ yum_automatic }}"
    service: "yum-cron"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int == 7

- name: "update − install {{ package }}"
  package: name="{{ package }}" state=present

- name: "update − copy {{ package }} configuration"
  template:
    src: automatic.conf.j2
    dest: "/etc/{{ config_path }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  vars:
    automatic: "{{ config_var }}"

- name: "update − enable {{ service }}"
  service: name="{{ service }}" state=started enabled=yes
