---
- name: Update − system packages
  ansible.builtin.package:
    name: "*"
    state: latest
    only_upgrade: true

- name: Update − install dnf-automatic
  ansible.builtin.package:
    name:
      - dnf-automatic
    state: present

- name: Update − copy dnf-automatic configuration
  ansible.builtin.template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  vars:
    automatic: "{{ dnf_automatic }}"

- name: Update − enable dnf-automatic.timer
  ansible.builtin.service:
    name: dnf-automatic.timer
    state: started
    enabled: true
